-- Generated by scripts/seed-sql.mts. Do not edit by hand.
insert into auth.users (id, email, raw_user_meta_data) values ('00000000-0000-4000-8000-000000000001', 'seed@modprompts.local', '{"full_name":"Modprompts"}') on conflict do nothing;
update profiles set handle = 'modprompts', display_name = 'Modprompts', role = 'admin' where id = '00000000-0000-4000-8000-000000000001';
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('context-fuel-gauge', '00000000-0000-4000-8000-000000000001', 'Context Fuel Gauge', 'A slim band above the prompt that shows how full your context window is, and how fast it fills.', 'Reads token usage after every request and draws a fuel bar with a burn rate. Turns amber at 70% and red at 90%, so you know when to compact before it bites.', 'Build me a Claude Code mod called context-fuel-gauge.

What it does: after every model request, read the token usage and show how full the context window is as a horizontal fuel bar, plus the average tokens used per turn and an estimate of turns left.
Where it shows: a one-line band above the prompt.
Events to hook: the request/response events that carry usage, and ui.render for the band.
State: the last 10 turns of input token counts, kept in module variables.
Look: a 20-cell bar using block characters, percentage on the right, then "burn X tok/turn · ~N turns left". Dim gray under 70%, amber 70-90%, red above 90%. Before the first request, show "waiting for first turn".
Commands: /fuel reset clears the history.
Limits: no network, no file writes, no model calls.
Done when: the bar moves after each turn and changes color at 70% and 90%; add a test with the mods test kit that feeds fake usage events and checks the color thresholds.

Use the plugin-authoring skill. Put it in ./context-fuel-gauge/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'context-tokens'), array['band']::text[], array['none']::text[], '2.1.287',
  'published', true, '2026-10-05T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('tool-call-counter', '00000000-0000-4000-8000-000000000001', 'Tool Call Counter', 'Adds a live count of tool calls to the spinner while Claude works.', 'The smallest useful mod. Counts every tool call in the current turn and writes it next to the spinner word, so long turns feel less like a black box.', 'Build me a Claude Code mod called tool-call-counter.

What it does: count the tool calls Claude makes in the current turn and show the count beside the spinner, like "Thinking · tool calls: 3…".
Where it shows: the spinner suffix.
Events to hook: tool.call to count, turn start to reset, ui.render with component ''Spinner'' to draw.
State: a single counter in a module variable.
Look: keep the original spinner, append " · tool calls: N…". Hide the suffix when N is 0.
Limits: no network, no files, no model calls. Always call next(e) so tools run as usual.
Done when: the number climbs during a multi-tool turn and resets on the next prompt; include a test that sends three tool.call events and checks the rendered suffix.

Use the plugin-authoring skill. Put it in ./tool-call-counter/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'monitoring'), array['spinner']::text[], array['none']::text[], '2.1.287',
  'published', false, '2026-10-04T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('blast-shield', '00000000-0000-4000-8000-000000000001', 'Blast Shield', 'Holds rm -rf, force pushes and DROP TABLE until you see what they would hit and say yes.', 'A guard for destructive shell commands. Instead of a plain permission prompt, it opens a pane that lists the files, branch or table the command touches, with Proceed and Cancel buttons.', 'Build me a Claude Code mod called blast-shield.

What it does: hold destructive Bash tool calls before they run and show what they would affect. Covers rm -rf, git push --force / -f, git reset --hard, git clean -fd, and SQL with DROP or TRUNCATE.
Where it shows: a pane beside the transcript that opens only while a command is held.
Events to hook: tool.call with a matcher for the Bash tool.
State: the held command and its preview.
Look: red header "HELD", the command in mono, then the impact: file count and size for rm (dry run with find), commits that would be lost for force push (git log remote..local), the table name for SQL. Two buttons: Proceed and Cancel. Enter = Proceed, Esc = Cancel.
Limits: previews must be read-only. Never run the held command yourself; Proceed just calls next(e). Time out after 5 minutes as Cancel.
Done when: "rm -rf ./tmp-test" is held with a correct file count, Cancel returns a refusal to Claude, Proceed runs it; tests cover the pattern matcher with 10 safe and 10 dangerous commands.

Use the plugin-authoring skill. Put it in ./blast-shield/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'safety'), array['guard', 'pane']::text[], array['files', 'processes']::text[], '2.1.287',
  'published', true, '2026-10-03T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('ci-radar', '00000000-0000-4000-8000-000000000001', 'CI Radar', 'A pane that watches the CI checks for your current branch and pings you when they flip.', 'Polls GitHub check runs for the branch you are on and lists them with live status. A toast fires when a check goes red or the whole run goes green.', 'Build me a Claude Code mod called ci-radar.

What it does: show the CI check runs for the current git branch and alert me when one fails or all pass.
Where it shows: a pane titled "CI", plus a toast on state changes.
Events to hook: session start to begin polling, a 30 second timer, ui.render for the pane.
State: the last known status of each check by name.
Look: branch name at the top, then one row per check: icon (✓ green, ✗ red, ● amber pulsing for running), name, duration. Empty state: "No checks for this branch yet".
Commands: /ci opens or closes the pane, /ci now forces a refresh.
Limits: use the gh CLI (gh pr checks or gh run list) through the mods process API; no tokens in code. Stop polling when the pane is closed for 10 minutes.
Done when: pushing a branch shows its checks within 30s and a failing check raises one toast; test the status-diff function that decides when to toast.

Use the plugin-authoring skill. Put it in ./ci-radar/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'git-ci'), array['pane', 'toast']::text[], array['network', 'processes']::text[], '2.1.287',
  'published', false, '2026-10-02T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('turn-cost-meter', '00000000-0000-4000-8000-000000000001', 'Turn Cost Meter', 'A status line with the cost of the last turn and the running total for the session.', 'Turns token usage into dollars using the model price table, and keeps a session total. Handy when you are on API billing and want to feel each turn.', 'Build me a Claude Code mod called turn-cost-meter.

What it does: after each turn, compute its cost from input, output and cache tokens, and keep a running session total.
Where it shows: the status line.
Events to hook: request completion events with usage, turn end.
State: session total, turn count, last turn cost.
Look: "last turn $0.042 · session $1.87 · 38 turns". Session total turns amber above a budget I set with /budget.
Commands: /budget 5 sets a $5 warning line, /budget off clears it.
Limits: keep the price table in one constant at the top of the file with a comment saying where it came from; no network.
Done when: numbers update after each turn; tests check the cost math for a cached and an uncached request.

Use the plugin-authoring skill. Put it in ./turn-cost-meter/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'context-tokens'), array['status']::text[], array['none']::text[], '2.1.287',
  'published', false, '2026-10-01T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('focus-timer', '00000000-0000-4000-8000-000000000001', 'Focus Timer', 'A pomodoro band that counts down while you pair with Claude and nudges you to take a break.', 'Start a 25 minute block with /focus. The band shows the countdown and how many turns you got through. When time is up, a toast tells you to stand up.', 'Build me a Claude Code mod called focus-timer.

What it does: a pomodoro timer inside Claude Code.
Where it shows: a band above the prompt while a block runs; a toast when it ends.
Events to hook: a 1 second timer while active, turn end to count turns, ui.render for the band.
State: end time, turns this block, completed blocks today.
Look: "◷ focus 18:42 left · 6 turns this block". Last minute blinks. Break mode uses a softer color and says "break 4:10".
Commands: /focus [minutes] starts (default 25), /focus stop, /focus stats shows blocks today.
Limits: no network, no files.
Done when: /focus 1 counts down and fires one toast at zero; test the time formatting and state transitions.

Use the plugin-authoring skill. Put it in ./focus-timer/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'productivity'), array['band', 'toast', 'command']::text[], array['none']::text[], '2.1.287',
  'published', false, '2026-09-30T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('todo-harvester', '00000000-0000-4000-8000-000000000001', 'TODO Harvester', 'Collects every TODO and FIXME Claude adds or touches, in a pane you can click through.', 'Watches file edits and pulls out TODO, FIXME and HACK comments in changed lines. The pane groups them by file so nothing Claude leaves behind gets lost.', 'Build me a Claude Code mod called todo-harvester.

What it does: after every Edit or Write tool call, scan the changed lines for TODO, FIXME and HACK comments and keep a list for this session.
Where it shows: a pane titled "TODOs" with a count.
Events to hook: tool result events for Edit, Write and MultiEdit; ui.render for the pane.
State: a map of file -> list of {line, tag, text}; drop entries whose line no longer contains the tag.
Look: grouped by file, each row "line  TAG  text", TAG colored (TODO yellow, FIXME red, HACK purple). Empty state: "Clean so far".
Commands: /todos toggles the pane, /todos ask sends a prompt to Claude asking it to resolve the list.
Limits: only read files Claude edited; no network.
Done when: an edit that adds "// TODO x" shows up in the pane within the same turn; test the comment parser on JS, Python and SQL comment styles.

Use the plugin-authoring skill. Put it in ./todo-harvester/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'workflow'), array['pane', 'command']::text[], array['files']::text[], '2.1.287',
  'published', false, '2026-09-29T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('branch-weather', '00000000-0000-4000-8000-000000000001', 'Branch Weather', 'Your git status as a tiny forecast in the status line: sunny, cloudy or stormy.', 'Summarizes uncommitted changes, ahead/behind counts and merge conflicts as a one glance weather report. Silly, and weirdly effective.', 'Build me a Claude Code mod called branch-weather.

What it does: show git status as weather.
Where it shows: the status line.
Events to hook: session start, turn end, and a 20 second timer.
State: the last status, so it only redraws when something changed.
Look: ☀ clean and in sync, ⛅ uncommitted changes, 🌧 behind remote, ⛈ merge conflicts. Then "branch · N files changed · ↑ahead ↓behind".
Limits: run only "git status --porcelain=v2 --branch"; no network fetches; show "no repo" outside git.
Done when: editing a file flips sun to cloud within 20s; test the porcelain parser on 4 sample outputs.

Use the plugin-authoring skill. Put it in ./branch-weather/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'fun-games'), array['status']::text[], array['processes']::text[], '2.1.287',
  'published', false, '2026-09-28T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('explain-this-edit', '00000000-0000-4000-8000-000000000001', 'Explain This Edit', 'A /why command that explains Claude''s last file edit in plain words, without a full turn.', 'Runs a small side model call on the last diff and prints a three line explanation: what changed, why, and what to check. Good for reviewing as you go.', 'Build me a Claude Code mod called explain-this-edit.

What it does: a /why command that explains the most recent file edit Claude made.
Where it shows: the command''s text reply.
Events to hook: tool result events for Edit/Write to remember the last diff; register the /why command.
State: the last diff (file path, old and new text), capped at 8k characters.
Look: three lines, "Changed:", "Why:", "Check:". If there is no edit yet, say so.
Limits: one small model call per /why using the mods model API with a cheap model; never send more than the stored diff.
Done when: after an edit, /why answers in under 5 seconds; test that the stored diff is truncated correctly.

Use the plugin-authoring skill. Put it in ./explain-this-edit/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'workflow'), array['command']::text[], array['model']::text[], '2.1.287',
  'published', false, '2026-09-27T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('test-runner-pane', '00000000-0000-4000-8000-000000000001', 'Test Runner Pane', 'Re-runs the tests touched by Claude''s edits and shows pass/fail in a pane.', 'Detects your test runner, finds tests related to the files Claude changed and runs only those after each turn. Red rows are clickable to send the failure back to Claude.', 'Build me a Claude Code mod called test-runner-pane.

What it does: after each turn with file edits, run the tests related to the changed files and show results.
Where it shows: a pane titled "Tests".
Events to hook: tool results for edits to collect changed files, turn end to run, ui.render for the pane.
State: changed files this turn, last results per test file.
Look: summary line "14 passed · 1 failed", then one row per test file with ✓/✗ and the first failure message. A button "Send failure to Claude" submits a prompt with the failure output.
Commands: /tests toggles the pane, /tests all runs the full suite.
Limits: detect the runner from package.json or pyproject (vitest, jest, pytest); run with a 2 minute timeout; never run if no runner is found.
Done when: breaking a test makes a red row appear after the turn; test the related-test lookup (foo.ts -> foo.test.ts, tests/test_foo.py).

Use the plugin-authoring skill. Put it in ./test-runner-pane/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'workflow'), array['pane', 'command']::text[], array['files', 'processes']::text[], '2.1.287',
  'published', true, '2026-09-26T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('quiet-hours', '00000000-0000-4000-8000-000000000001', 'Quiet Hours', 'Blocks deploys, pushes to main and prod migrations outside the hours you set.', 'A policy guard for people who ship from the terminal. Outside your working window it refuses risky commands with a clear reason Claude can read.', 'Build me a Claude Code mod called quiet-hours.

What it does: outside a configured time window, refuse Bash commands that deploy or push to protected branches.
Where it shows: a status line "🌙 quiet hours until 09:00" while active; refusals appear as the tool result Claude reads.
Events to hook: tool.call for Bash.
State: none beyond config.
Look: refusal text: "Blocked by quiet-hours: <command>. Allowed 09:00-18:00 Mon-Fri."
Limits: config via plugin userConfig (window, days, patterns). Default patterns: git push to main/master, vercel --prod, fly deploy, kubectl apply, prisma migrate deploy. No network.
Done when: at 23:00 a push to main is refused and a push to a feature branch is not; test the time window logic across midnight and the pattern list.

Use the plugin-authoring skill. Put it in ./quiet-hours/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'safety'), array['guard', 'status']::text[], array['none']::text[], '2.1.287',
  'published', false, '2026-09-25T00:00:00.000Z') on conflict (slug) do nothing;
insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values ('prompt-time-machine', '00000000-0000-4000-8000-000000000001', 'Prompt Time Machine', 'Search every prompt you sent this week and resend one with a keystroke.', 'Keeps a local history of your prompts across sessions. /history opens a searchable pane; pick one to drop it back in the prompt box.', 'Build me a Claude Code mod called prompt-time-machine.

What it does: save every prompt I submit with a timestamp and project path, and let me search and reuse them.
Where it shows: a pane opened by /history with a search field and a result list.
Events to hook: prompt submit to record; register /history; ui.render for the pane.
State: history file at ~/.claude/prompt-history.jsonl, last 2,000 entries; in-memory index while the pane is open.
Look: search box on top, rows "age  first 80 chars", current project first. Enter puts the prompt into the input box, it does not send it.
Limits: only write to that one file; skip prompts that look like secrets (long base64 or "sk-" prefixes).
Done when: a prompt from yesterday is found by a word in it and lands in the input box; test the secret filter and the search ranking.

Use the plugin-authoring skill. Put it in ./prompt-time-machine/ as a plugin with
.claude-plugin/plugin.json, hooks/hooks.json and hooks/register.ts,
then load it with /reload-plugins.',
  (select id from categories where slug = 'productivity'), array['pane', 'command']::text[], array['files']::text[], '2.1.287',
  'published', false, '2026-09-24T00:00:00.000Z') on conflict (slug) do nothing;
