// Generates supabase/seed.sql from content/seed-mods.ts.
// Run: npm run seed:sql
import { SEED_MODS } from '../content/seed-mods.ts'

const AUTHOR_ID = '00000000-0000-4000-8000-000000000001'
const q = (s: string | null | undefined) => (s == null ? 'null' : `'${s.replace(/'/g, "''")}'`)
const arr = (a: string[]) => `array[${a.map(q).join(', ')}]::text[]`

const out = [
  '-- Generated by scripts/seed-sql.mts. Do not edit by hand.',
  `insert into auth.users (id, email, raw_user_meta_data) values (${q(AUTHOR_ID)}, 'seed@modprompts.local', '{"full_name":"Modprompts"}') on conflict do nothing;`,
  `update profiles set handle = 'modprompts', display_name = 'Modprompts', role = 'admin' where id = ${q(AUTHOR_ID)};`,
  ...SEED_MODS.map(
    m => `insert into mods (slug, author_id, title, tagline, description_md, prompt_md, category_id, surfaces, reaches, min_cc_version, status, is_featured, published_at)
values (${q(m.slug)}, ${q(AUTHOR_ID)}, ${q(m.title)}, ${q(m.tagline)}, ${q(m.descriptionMd)}, ${q(m.promptMd)},
  (select id from categories where slug = ${q(m.category?.slug)}), ${arr(m.surfaces)}, ${arr(m.reaches)}, ${q(m.minCcVersion)},
  'published', ${m.isFeatured}, ${q(m.publishedAt)}) on conflict (slug) do nothing;`,
  ),
]
console.log(out.join('\n'))
